version: '3.7'

services:
  db-mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "test_database"
      MYSQL_USER: "test_user"
      MYSQL_PASSWORD: "secret"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
    ports:
      - '3306:3306'
    expose:
      - '3306'

  app-go:
    build: ./
    depends_on:
      db-mysql:
        condition: service_healthy
    ports:
      - "8080:8080"