version: '3.7'

services:
  db-mysql:
    image: mysql:8.0.28
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "praktikum"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
    ports:
      - '3306:3306'
    expose:
      - '3306'

  app-go:
    build: ./
    depends_on:
      db-mysql:
        condition: service_healthy
    environment:
      # APIPort: "8080"
      DB_USERNAME: "root"
      DB_PASSWORD: "root"
      DB_HOST: "db-mysql"
      DB_PORT: "3306"
      DB_NAME: "praktikum"

    ports:
      - "8080:8080"